objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: smoggy-tomatoes
    name: s2i-java
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: fabric8/s2i-java
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ''
  status:
    dockerImageRepository: ''
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: smoggy-tomatoes
    name: smoggy-tomatoes-backend
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: smoggy-tomatoes
    name: smoggy-tomatoes-backend
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: smoggy-tomatoes-backend:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
      contextDir: backend
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-java:latest
        incremental: true
        env:
        - name: JAVA_APP_JAR
          value: my-app-runner.jar
        - name: ARTIFACT_COPY_ARGS
          value: -p -r lib/ my-app-runner.jar
      type: Source
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: smoggy-tomatoes
    name: smoggy-tomatoes-backend
  spec:
    replicas: 1
    selector:
      app: smoggy-tomatoes
      deploymentconfig: smoggy-tomatoes-backend
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: smoggy-tomatoes
          deploymentconfig: smoggy-tomatoes-backend
      spec:
        containers:
        - image: smoggy-tomatoes-backend:latest
          name: smoggy-tomatoes-backend
          ports:
          - containerPort: 9779
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 3
          env:
          - name: JAVA_APP_JAR
            value: my-app-runner.jar
          - name: ARTIFACT_COPY_ARGS
            value: -p -r lib/ my-app-runner.jar
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - smoggy-tomatoes-backend
        from:
          kind: ImageStreamTag
          name: smoggy-tomatoes-backend:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: smoggy-tomatoes
    name: smoggy-tomatoes-backend
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779
    selector:
      app: smoggy-tomatoes
      deploymentconfig: smoggy-tomatoes-backend
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: smoggy-tomatoes-backend
    labels:
      app: smoggy-tomatoes
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: smoggy-tomatoes-backend
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/dummy_org/dummy_repo
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: The secret used to configure a GitHub webhook
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
apiVersion: template.openshift.io/v1
kind: Template
